### ISSUE TITLE
Dockerの環境用のスクリプト作成

### ISSUE THREAD

**Issue by PalmNeko** [subarunrun0812/python_automation_contest_2days#6]

**Comment by PalmNeko** [comment]
**参考**
* [ファイルのディレクトリパスを取得](https://qiita.com/koara-local/items/2d67c0964188bba39e29)
* [DockerfileのRUNについて](https://qiita.com/sky0621/items/d837c566b04464469fdb)
* [Dockerfileのビルド](https://www.isoroot.jp/blog/4714/)
* [Dockerfileの書き方](https://qiita.com/gon0821/items/f9e3bcbb6cb01d4ef7fa#%EF%BC%93-cmd)

* [Docker環境の構築](https://github.com/subarunrun0812/python_automation_contest_2days/wiki/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89)

**Comment by subarunrun0812** [comment]
### SSH接続
1. `bash start-docker.sh`
2. 別ターミナルで`ssh -X -p 2222 root@localhost`
3. パスワード `password` を入力

**Comment by subarunrun0812** [comment]
動かん！！！！！！！
pythonでwindowを表示させるから、GUIが表示できる環境を整える必要がある。
時間もないので、今回は諦め。
```
root@9da836486456:/home# python srcs/app.py
Traceback (most recent call last):
  File "/home/srcs/app.py", line 15, in <module>
    app = tk.Tk()
          ^^^^^^^
  File "/usr/local/lib/python3.12/tkinter/__init__.py", line 2340, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: couldn't connect to display "localhost:10.0"
```
